/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SokhanchakImport } from './routes/sokhanchak'

// Create/Update Routes

const SokhanchakRoute = SokhanchakImport.update({
  id: '/sokhanchak',
  path: '/sokhanchak',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sokhanchak': {
      id: '/sokhanchak'
      path: '/sokhanchak'
      fullPath: '/sokhanchak'
      preLoaderRoute: typeof SokhanchakImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/sokhanchak': typeof SokhanchakRoute
}

export interface FileRoutesByTo {
  '/sokhanchak': typeof SokhanchakRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/sokhanchak': typeof SokhanchakRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sokhanchak'
  fileRoutesByTo: FileRoutesByTo
  to: '/sokhanchak'
  id: '__root__' | '/sokhanchak'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SokhanchakRoute: typeof SokhanchakRoute
}

const rootRouteChildren: RootRouteChildren = {
  SokhanchakRoute: SokhanchakRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/sokhanchak"
      ]
    },
    "/sokhanchak": {
      "filePath": "sokhanchak.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
